proposed fix to #39244
freeCodeCamp/boilerplate-page-view-time-series-visualizer pull request #3
Opened 2020-10-02 18:16 UTC by ricknjacky

added the numeric-only=True argument to the method as advised

2020-10-02 18:31 UTC, RandellDawson commented
@ricknjacky Does this PR related to a reported outstanding issue?  If so, can you please provide the link to the issue?  Thank you.

2020-10-02 18:45 UTC, ricknjacky commented
yes @RandellDawson this does correspond to an outstanding issue #39244 link:- [#39244](https://github.com/freeCodeCamp/freeCodeCamp/issues/39244#issue-656076354 )

2020-10-04 10:34 UTC, Sky020 requested changes
Thank you, for this PR. Do note: without this change, the code reads as:
> numeric `<minus>` only `<equals>` True

2020-10-04 10:34 UTC, Sky020 commented on test_module.py
> +        actual = int(time_series_visualizer.df.count(numeric-only=True))
```suggestion
        actual = int(time_series_visualizer.df.count(numeric_only=True))
```

2020-10-05 08:52 UTC, ricknjacky commented
please review @Sky020

2020-10-05 12:38 UTC, Sky020 approved these changes
This LGTM 👍 . Thank you, for making that change.

@RandellDawson Does the workflow for these projects require the _fCC repl.it_ project to be updated? Or, is the boilerplate the only code cloned?

2020-10-09 05:48 UTC, scissorsneedfoodtoo commented
Thanks for submitting this PR @ricknjacky, and for your quick review @Sky020. Also, thanks for suggesting the change we'll use for the test @Sky020.

This seems to solve the issue mentioned in https://github.com/freeCodeCamp/freeCodeCamp/issues/39244#issuecomment-702428750. Everything LGTM :+1: :+1: 

I'll go ahead and merge this and make sure the change is reflected on Repl.it, just in case someone forks the boilerplate from there.

2020-10-09 05:48 UTC, scissorsneedfoodtoo approved these changes

2020-10-09 05:48 UTC, merged