Proposed change of example image
freeCodeCamp/boilerplate-page-view-time-series-visualizer pull request #5
Opened 2021-05-30 09:18 UTC by kkralik

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #42307

As pointed out in the issue description, the provided example plot is a little different from a plot provided by a code passing the tests.
* Different Y axis limit
* Different shape of Seasonal part of plot

I am sorry if the merging attempt is somehow wrong, I am very new here.
I forked the repository, created a new branch, but the merging is a bit confusing and I am not convinced I am doing it right. Any feedback will be much appreciated.

The new figure has a different name, because when I uploaded new figure with the same name the old one had, GitHub assumed it's reuploading the same one and just 'reversed the deletion' somehow. I will be very grateful for any advice on this, too (so I know how to deal with it in the future).
I suspect it might get resolved by either of:
*  making one branch for deletion and then one for new figure
*  making the change like this and in the next commit renaming the file

2021-06-01 14:03 UTC, gikf requested changes
Not sure about file github being confused about new file, either way having one commit for deletion, adding, and then renaming to the previous name should be fine. Commits in the PR will be squashed anyway - if merged, all changes from the PR will appear as single commit on the main branch.

There's one thing off on the changed plot. On the right plot `x` labels are set to be ordered months, but the value on plot is not from the given month, This is visible after commenting out the following line:
```python
    right.set_xticklabels(month_names_short)
```

One way of dealing with it would be using optional `order` argument in the second `sns.bloxplot` call.

2021-06-02 10:23 UTC, kkralik commented
Hello,
thank you for your feedback!
I have had a look into it and I figured out that right.set_xlabels was a piece of forgotten code  from previous version, which now kept this hidden (it was added, because originally my x axis only had numbers and this added text). I think I need to be more vigilant when rewriting code after a larger change, and check my values multiple times when plotting. I'll rework my submission code as well, but I'll post the updated version for this plot here.
The current picture should be:
![image](https://user-images.githubusercontent.com/75544188/120460632-331aca00-c391-11eb-80ba-311f3ed99364.png)
It's still very different from the provided one, but should be in the right order (I checked by looking at means)

The current code producing Figure_3.png as added now (2.6.2021 - for some reason now I can upload it with the original name, maybe I was checking the image in a wrong branch before) is:
```
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()

# Import data (Make sure to parse dates. Consider setting index column to 'date'.)
df = pd.read_csv("fcc-forum-pageviews.csv", index_col="date", parse_dates = True)

# Clean data
df = df.loc[(df["value"] <= df['value'].quantile(0.975)) & (df["value"] >= df['value'].quantile(0.025))]

month_names_long = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
month_names_short = [m[0:3] for m in month_names_long]
ys = [n for n in range(0,200001, 20000)]

def draw_box_plot():
    ### Prepare data for box plots (this part is done!) - PROFIDED BY FCC, AttributeError
    df_box = df.copy()
    df_box.reset_index(inplace=True)
    df_box['year'] = [d.year for d in df_box.date]
    df_box['month'] = [d.strftime('%b') for d in df_box.date]

    # Draw box plots (using Seaborn)
    fig = plt.figure(figsize=(40, 15))
    left = plt.subplot(121)
    sns.boxplot(x = 'year', y = 'value', data = df_box)
    plt.yticks(ys, ys)

    left.set(xlabel = 'Year', ylabel = 'Page Views', title = 'Year-wise Box Plot (Trend)')

    right = plt.subplot(122)
    sns.boxplot(x = 'month', y = 'value', data = df_box, order=month_names_short)
    right.set(xlabel = 'Month', ylabel = 'Page Views', title = 'Month-wise Box Plot (Seasonality)')
    
    plt.yticks(ys, ys)
   
    fig.tight_layout(pad=3.0)


    # Save image and return fig (don't change this part)
    fig.savefig('box_plot.png')
    return fig
```

I hope it's ok this way, thank you again for your time! Have a lovely day.

2021-06-02 14:16 UTC, gikf approved these changes
Thanks for update, image looks now correct to me. LGTM :+1:

2021-06-02 14:37 UTC, raisedadead approved these changes

2021-06-02 14:38 UTC, merged